
- name: Docker Build and Push
  hosts: localhost  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/PETSHOP

    - name: Tag Image
      command: docker tag petstore:latest waounde221/petstore:latest

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: waounde221
        password: dckr_pat_kG-CeKsE8VAHMRNexHVa7Es3a9k

    - name: Push Image
      command: docker push waounde221/petstore:latest

    - name: Run Container
      command: docker run -d --name pet1 -p 8081:8080 waounde221/petstore:latest
