---
- name: Deploy Kubernetes Application
  hosts: k8s  # Replace with your target Kubernetes master host or group
  gather_facts: yes  # Gather facts about the target host

  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/PETSHOP/deployment.yaml  # Assuming Jenkins workspace variable
        dest: /home/vagrant/
      become: yes  # Use sudo for copying if required
      become_user: vagrant  # Use the appropriate user for copying if required

    - name: Apply Deployment
      command: kubectl apply -f /home/vagrant/deployment.yaml
